### PR TITLE
Use number of passed arguments to trigger overload

### LINKED ISSUE #2: `hasState` reports `false` when state is `undefined`
I found this surprising, though I guess it might be intended.

### PR DESCRIPTION
**Pull request by zenparsing**
Fixes #2 

I was worried about performance of using a rest arg but it seems to be comparable when testing on Node.

### CODE REVIEW

**Comment by zenparsing** [comment]
@bakkot Do you think this is better?

**Comment by bakkot** [comment]
I personally think so, yeah. Though I don't have a good sense of how anyone else would expect it to work, so don't weight my opinion very heavily. This PR does make the overload work more like spec methods (like `Array.prototype.reduce`), which is an argument in favor.

(This didn't actually come up in my [one actual use case](https://github.com/bakkot/frozen-set/blob/d74a7592b43ff0e242f94060b9de7d3999a36b18/really-frozen.js) so far; it was just something I noticed when playing with it.)

**Comment by zenparsing** [comment]
Published in `1.1.1`.

BTW, I'm really interested in how this library will work with another idea of mine: a "call-with" binary operator `->` that calls the RHS with the LHS as first argument:

```js
const hidden = hiddenState('X');

class X {
  constructor() {
    this->hidden(42);
  }

  speak() {
    return this->hidden();
  }
}

```

If WeakMaps were more performant (or if hiddenState was backed by something map like that was more performant) then... 😎

**Comment by bakkot** [comment]
Ooh, neat. Though, with that syntax it seems weirder to me to have the overloads rather than distinct "get" and "set" functions. (Maybe I'm just too used to Java these days...)

**Comment by zenparsing** [comment]
I suppose it could look something like this:

```js
const [getState, setState, hasState] = hiddenState('X');

class X {
  constructor() {
    this->setState(42);
  }

  speak() {
    return this->getState();
  }
}
```

**Pull request merged**
